### ISSUE TITLE
Some small issues

### ISSUE THREAD

**Issue by LZ-Ekul** [dickloraine/xenos-rampant-builder#3]
Hey,

First off let me say, excellent job with this army builder! I've been using it since I started playing about 3 months ago and it's been a great help.

I've noticed a couple of problems with some of the options and xeno rules, as noted below;

Elite options;
Super heavy armour (SHA) - lowers movement by 2", however, when you then take Mobile it jumps back up to 12" (base 8+4). If you take Mobile first then SHA it drops the stats down to 6" (base 8-2).

Same issue as above but with the Slow Xeno rule. Slow ends up having no effect after SHA has been selected.

Xeno rule;
Psychic Resistance adds the information of psychic hazards.

Thank you for taking the time to look at my message.

Luke

**Comment by LZ-Ekul** [comment]
Just an additional issue, when you select swarm upgrade for lesser xenomorphs it doesn't apply the strength point upgrade.

I hope you don't mind me bringing these little things to your attention.

Thanks again,
Luke

**Comment by dickloraine** [comment]
Thanks for the kind words. The issues should be fixed now. If you load the app the next time, it should update. After you close it and reopen it, the issues should be gone.
