### ISSUE TITLE
Units with Psychic Species and Psychic Rules Raise Error

### ISSUE THREAD

**Issue by joebobmiles** [dickloraine/xenos-rampant-builder#5]
There's a bug in the validation code that checks if a unit with the Psychic Species xenos rule already has the Psychic xenos rule. When a unit has both, it complains that only Psychic units can have Psychic Species:

![image](https://github.com/dickloraine/xenos-rampant-builder/assets/19335924/95b2930c-391f-4ec0-81c1-461aefd9ab31)

But when the unit doesn't have Psychic:

![image](https://github.com/dickloraine/xenos-rampant-builder/assets/19335924/ee1b0b1e-19e8-4986-9388-741dbfe879ae)

Took a look and seems likes there's a double negative in [Validation.ts](https://github.com/dickloraine/xenos-rampant-builder/blob/61ebfd8c168b43af526f98ca112986d436ec32b4/src/components/Validation.tsx#L22C5-L22C5)

```ts
const isPsycher = !unit.xenosRules.some((x) =>
  ['Psychic 1', 'Psychic 2', 'Psychic 3', 'Psychic 4'].includes(x)
);
```

And later:

```ts
if (
  (unit.xenosRules.includes('Psychic Species 1') ||
    unit.xenosRules.includes('Psychic Species 2') ||
    unit.xenosRules.includes('Psychic Species 3')) &&
  !isPsycher
)
  warnings.push([unit.name, 'Only a psychic unit can take Psychic Species!']);
```

Simple fix is to change line 22 to remove the negation:

```ts
const isPsycher = unit.xenosRules.some((x) =>
  ['Psychic 1', 'Psychic 2', 'Psychic 3', 'Psychic 4'].includes(x)
);
```

I'll submit a pull request in a bit, unless you beat me to it.

**Comment by dickloraine** [comment]
Thanks for the pull request. Stupid copy/paste errors :)
